### ISSUE TITLE
Error when running in docker desktop for windows 4.25

### ISSUE THREAD

**Issue by ivanmaia** [sergioprates/kindxt#24]
I was experiencing an error when running kindxt with Docker Desktop for Windows version 4.25.0.

The workaround that worked fopr me here was to change the kindest/node image version inside kind's config file `kindxt\publish\Kind\config.yaml`.

In my case I changed from ```kindest/node:v1.26.0@sha256:691e24bd2417609db7e589e1a479b902d2e209892a10ce375fab60a8407c7352``` to ```kindest/node:v1.27.3@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72```.

**Comment by sergioprates** [comment]
I had errors here as well. To track the history purposes:
`[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
I1112 17:54:45.520236     135 round_trippers.go:553] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds
I1112 17:54:46.021705     135 round_trippers.go:553] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds
I1112 17:54:46.522048     135 round_trippers.go:553] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds
I1112 17:54:47.020958     135 round_trippers.go:553] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds
I1112 17:54:47.521024     135 round_trippers.go:553] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds`

Maybe we should consider the 1.27 image as default.

**Comment by sergioprates** [comment]
This commit should solve it. I updated the image version to 1.28 here 1f8eda7ea2d75829ca2f040b894ed184b2e3d3c4
