### ISSUE TITLE
Option --citus is not working yet

### ISSUE THREAD

**Issue by ivanmaia** [sergioprates/kindxt#4]
I'm using this as a workaround:

After creating a cluster using the ```--pssql``` option:
1) > helm uninstall postgres
2) > git clone https://github.com/sergioprates/citus-chart
3) > cd citus-chart/citus
4) > kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.5.4/cert-manager.yaml
5) > helm install citus .

**Comment by igor-couto** [comment]
I'm looking forward to see this feature!
